### ISSUE TITLE
Unmatched Request Error

### ISSUE THREAD

**Issue by xwiz** [enyata/innovation-sandbox-scripts#2]
Hi, I get the following error when I make a request to `/nibss/bvnr/VerifySingleBVN`. I have also cross-checked the code with the documentation and everything seems right. 

```
{ 
   "ResponseCode":"05",
   "Message":"Unmatched Request, Refer to documentation.",
   "EXPECT":{ 
      "header":{ 
         "Accept":[ 
            "application/json",
            "application/xml"
         ],
         "Content-Type":[ 
            "application/json",
            "application/xml"
         ],
         "OrganisationCode":"MTExMTE=",
         "Authorization":"MTExMTE6Xm8nZTZFWEs1VCB+XmoyPQ==",
         "SIGNATURE":"13c4c407aee080b05ba0e658529e0bb7b218a56531cb409a94e3323f9f7c719e",
         "SIGNATURE_METH":"SHA256"
      },
      "body":{ 
         "BVN":"12345678901"
      }
   }
}
```

**Comment by akinjide** [comment]
Hello, which of the scripts did you execute to get this error?

**Comment by xwiz** [comment]
@akinjide The node script.

**Comment by akinjide** [comment]
Can you post the structure of your request or paste a remote editor link?

**Comment by xwiz** [comment]
Hmm the script is already in the repo. I only modified the first line to use https and followRedirects, then changed host and variables accordingly.

**Comment by akinjide** [comment]
Please try again with Go script while I debug the node script

**Comment by xwiz** [comment]
OK will check, thank you

**Comment by akinjide** [comment]
@xwiz The node script has been updated. You can try that again and run with node@10.15 or higher. https://github.com/enyata/innovation-sandbox-scripts/blob/master/nibss/node/index.js

**Comment by xwiz** [comment]
Thank you, just tried this and got the same error. I also realized the real cause of the error is putting a live bvn. Shouldn't say `Unmatched request, refer to documentation` nevertheless.

**Comment by akinjide** [comment]
yeah, a live bvn will throw errors because the hostname is a mock/sandbox. Closing this issue.

**Comment by xwiz** [comment]
Simply closing doesn't fully solve the problem. The documentation should include the test BVNs and since it's a sandbox API, I think a proper matching error message should be returned. Thank you for your help.

**Comment by akinjide** [comment]
The documentation does give testing BVNs although it might be unclear and we will work to update it. However, the sandbox API returned an error indicating the request didn't match the expected if you check again.

I will think of this scenario like assert(EXPECT, ACTUAL) where the sandbox has expectations you will need to satisfy and those expectations match the required request from the production system.
